# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BBL-desktop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  platform :osx, '10.13'

  # Pods for BBL-desktop
end

target 'BBL-mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  platform :ios, '9.0'

  # Pods for BBL-mobile
  pod 'GoogleMobileAdsMediationAdColony'
end
